// -------------- start if imports ---------------//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//---------------- end of imports ------------//

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ start @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
namespace Programming_7312_Part_1.Models
{
    
    /// Represents an announcement entity used for displaying important information or notifications in the application.
    /// This model is mapped to the database and includes properties for title, content, category, dates, and priority.
    
    public class Announcement
    {
        
        /// Gets or sets the unique identifier for the announcement.
        /// This is the primary key and is auto-generated by the database.
        
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        
        /// Gets or sets the title of the announcement.
        /// This field is required and has a maximum length of 200 characters.
        
        [Required]
        [MaxLength(200)]
        public string? Title { get; set; }

       
        /// Gets or sets the main content or body of the announcement.
        /// This field is required and has a maximum length of 2000 characters.
        
        [Required]
        [MaxLength(2000)]
        public string? Content { get; set; }

        
        /// Gets or sets the category of the announcement (e.g., "News", "Alert", "Update").
        /// This field is optional and has a maximum length of 100 characters.
        
        [MaxLength(100)]
        public string? Category { get; set; }


        /// Gets or sets the date and time when the announcement was created.
        /// Defaults to the current date and time if not specified.
      
        public DateTime CreatedDate { get; set; } = DateTime.Now;

       
        /// Gets or sets the optional expiry date for the announcement.
        /// After this date, the announcement may no longer be displayed.
       
        public DateTime? ExpiryDate { get; set; }

        
        /// Gets or sets a value indicating whether the announcement is active and should be displayed.
        /// Defaults to true (active).
        
        public bool IsActive { get; set; } = true;

      
        /// Gets or sets the priority level of the announcement.
        /// Values: 1=Low, 2=Medium, 3=High. Defaults to 1 (Low).
       
        public int Priority { get; set; } = 1;
    }
}
//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ end  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@